add selectable levelhead mode
Intro-Dev/Osmium pull request #36
Opened 2022-02-17 20:00 UTC by moehreag

Created in collaboration with @Lolonaut679 (he wants to learn java)
![image](https://user-images.githubusercontent.com/85403855/154560912-e8ba202a-e32b-4205-a4c7-ec93d27ef624.png)

Modes until now: 
	- Network Level
	- Bedwars Level
	- Skywars Level

2022-02-19 00:40 UTC, Intro-Dev requested changes
Looks good, other than the println in there

2022-02-19 00:40 UTC, Intro-Dev commented on src/main/java/com/intro/client/util/HypixelAbstractionLayer.java
> +               System.out.println(cachedPlayerData.get(uuid).get(1, TimeUnit.MICROSECONDS).getPlayer().getRaw());
This prints gotta be removed

2022-02-19 09:18 UTC, moehreag commented on src/main/java/com/intro/client/util/HypixelAbstractionLayer.java
> +               System.out.println(cachedPlayerData.get(uuid).get(1, TimeUnit.MICROSECONDS).getPlayer().getRaw());
I really don't know how that slipped through..

2022-04-09 15:05 UTC, Intro-Dev approved these changes
Looks good

2022-04-09 15:10 UTC, merged